#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if package.json or package-lock.json have changed
if git diff --name-only $1 $2 | grep -q "package.json\|package-lock.json"; then
  echo "📦 Package files changed. Installing dependencies..."
  npm install
  echo "✅ Dependencies installed successfully!"
fi
